---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (Amazon Linux - CentOS)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Amazon"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      state: present
      key: "{{ lookup('file','~/.ssh/id_ed25519_simone_ansible.pub') }}"
      
- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.2.3/terraform_1.2.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
      
- hosts: web_servers
  become: true
  tasks:
  - name: install apache and php for Ubuntu servers
    tags: apache, apache2, ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for Amazon Linux - CentOS servers
    tags: apache, centos, httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

  - name: start httpd (Amazon Linux - CentOS)
    tags: apache, centos, httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "Amazon"

  - name: change email address for apache server admin
    tags: apache, centos, httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin root@localhost
    when: ansible_distribution == "Amazon"
    register: variable_whose_name_does_not_matter

  - name: restart httpd (Amazon Linux - CentOS)
    tags: apache, centos, httpd
    service:
      name: httpd
      state: restarted
    when: variable_whose_name_does_not_matter.changed

  - name: copy default html file for site
    tags: apache, apache2, htppd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
      
- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Amazon Linux - CentOS)
    tags: centos, db, mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "Amazon"

  - name: install mariadb package (Ubuntu)
    tags: db, mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
