---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (Amazon Linux - CentOS)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Amazon"

  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      state: present
      key: "{{ lookup('file','~/.ssh/id_ed25519_simone_ansible.pub') }}"

- hosts: all
  become: true
  roles:
  - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

