- name: install apache and php for Ubuntu servers
  tags: apache, apache2, ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache and php for Amazon Linux - CentOS servers
  tags: apache, centos, httpd
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "Amazon"

- name: start httpd (Amazon Linux - CentOS)
  tags: apache, centos, httpd
  service:
    name: httpd
    state: started
  when: ansible_distribution == "Amazon"


- name: change email address for apache server admin
  tags: apache, centos, httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin root@localhost
  when: ansible_distribution == "Amazon"
  register: variable_whose_name_does_not_matter

- name: restart httpd (Amazon Linux - CentOS)
  tags: apache, centos, httpd
  service:
    name: httpd
    state: restarted
  when: variable_whose_name_does_not_matter.changed

- name: copy default html file for site
  tags: apache, apache2, htppd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
