- name: install mariadb package (Amazon Linux - CentOS)
  tags: centos, db, mariadb
  yum:
    name: mariadb
    state: latest
  when: ansible_distribution == "Amazon"

- name: install mariadb package (Ubuntu)
  tags: db, mariadb, ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
